### ISSUE TITLE
How to remove dependency on photos.json?

### ISSUE THREAD

**Issue by TinajaLabs** [travishorn/photo-gallery#1]
This looks like a very clean implementation of a gallery site.  I’ve got something on the order of 30,000 images in cascading albums/folders. Can you suggest a way to autofill the photos.json file? Or alternatively, how would one just read the files directly from disk and not require the photos.json file?

Thank you for any advice,
Chris.

**Comment by travishorn** [comment]
I went into detail about this here: https://medium.com/@travishorn/chris-88a6aed32bad
